---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-predict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-predict
  template:
    metadata:
      labels:
        app: mlflow-predict
    spec:
      containers:
      - name: mlflow-predict
        image: hannibal133/predspod:test
        imagePullPolicy: "Always"
        ports:
          - containerPort: 5001
        command: ["/bin/sh"]
        args: ["-c", "mlflow models serve -m s3://mlflowtrackingserver/0/0297fcd1ff454acf9344738d1c6efd84/artifacts/model --host 0.0.0.0 --port 5001"]

...

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-predict
  labels:
    app: mlflow-predict
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: mlflow-predict