apiVersion: apps/v1
kind: Deployment
metadata:
  name: asdf1234
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asdf1234
  template:
    app: asdf1234
    metadata:
      labels:
        app: asdf1234
    spec:
      containers:
      - args:
        - -c
        - mlflow models serve -m s3://mlflowtrackingserver/45/asdf1234/artifacts/model
          --host 0.0.0.0 --port 5001
        command:
        - /bin/sh
        image: 475452188481.dkr.ecr.us-east-2.amazonaws.com/mlflow:prediction
        imagePullPolicy: Always
        name: asdf1234
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: asdf1234
  name: asdf1234
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: asdf1234
  type: LoadBalancer
