apiVersion: apps/v1
kind: Deployment
metadata:
  name: e0ef407d89d9459ea30d71b9112cfe4e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e0ef407d89d9459ea30d71b9112cfe4e
  template:
    app: e0ef407d89d9459ea30d71b9112cfe4e
    metadata:
      labels:
        app: e0ef407d89d9459ea30d71b9112cfe4e
    spec:
      containers:
      - args:
        - -c
        - mlflow models serve -m s3://mlflowtrackingserver/0/e0ef407d89d9459ea30d71b9112cfe4e/artifacts/model
          --host 0.0.0.0 --port 5001
        command:
        - /bin/sh
        image: hannibal133/predspod:test
        imagePullPolicy: Always
        name: e0ef407d89d9459ea30d71b9112cfe4e
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: e0ef407d89d9459ea30d71b9112cfe4e
  name: pod-e0ef407d89d9459ea30d71b9112cfe4e
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: e0ef407d89d9459ea30d71b9112cfe4e
  type: NodePort
